### ISSUE TITLE
Using next.config.js in favor of custom server

### ISSUE THREAD

**Issue by kvnang** [Automattic/vip-go-nextjs-skeleton#45]
Using custom server doesn't seem to be necessary, as proxying / rewriting can be easily done on `next.config.js`, or at most using Middleware API (requires Next.js 12) if more complex operation is necessary.

Is there a reason why custom server would be necessary for VIP?

## Reason
Custom server implementation is no longer recommended by Next.js, and is missing out certain features like Automatic Static Optimization. I can only imagine that future versions of Next.js will distance itself further from custom server.

## Example
For example, the following redirection for preview on `server/index.js`

```
server.get( '*', ( req, res, nextMiddleware ) => {
  if ( 'true' === req.query.preview && req.query.preview_id || req.query.p ) {
    const query = req.url.substr( req.url.indexOf( '?' ) );
    return res.redirect( 302, `${wordPressEndpoint}${query}` );
  }
  
  // Pass the request to the next middleware for evaluation.
  nextMiddleware();
} );
```

can be converted into the following on `next.config.js`
```
async redirects() {
  return [
    {
      source: '/:path*',
      has: [
        {
          type: 'query',
          key: 'preview',
          value: 'true',
        },
        {
          type: 'query',
          key: 'preview_id',
        },
      ],
      permanent: true,
      destination: `${wordPressEndpoint}/:path*`,
    },
    {
      source: '/:path*',
      has: [
        {
          type: 'query',
          key: 'preview',
          value: 'true',
        },
        {
          type: 'query',
          key: 'p',
        },
      ],
      permanent: true,
      destination: `${wordPressEndpoint}/:path*`,
    },
  ],
}
```

Happy to help with PR if needed.

**Comment by chriszarate** [comment]
Hi Kevin! Thanks for opening this issue. A custom server can often be avoided, but it can be needed to implement more complicated redirection or proxying logic. We therefore decided to provide a working custom server implementation out of the box for customers that need to pursue this kind of functionality.

I agree that a pure config-driven approach is better, so thank you for providing an example that other customers can consider and use. :)

**Comment by kvnang** [comment]
That makes sense @chriszarate! Thanks!
